packages:
  # Core packages
  - 'packages/*'            # All packages in the packages directory
  
  # Applications
  - 'apps/*'               # All applications
  
  # Exclude directories
  - '!**/dist'             # Exclude all dist directories
  - '!**/build'            # Exclude all build directories
  - '!**/node_modules'     # Exclude all node_modules directories
  - '!**/test'             # Exclude test directories from workspace