blank_issues_enabled: true
contact_links:
  - name: animate-ui
    url: https://mindfiredigital.github.io/animate-ui/
    about: TextIgniterJS is a tool that allows developers to integrate HTML Editor using Typescript.
